# Generated by Django 2.2.11 on 2021-04-21 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200716_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Name', models.CharField(max_length=200, verbose_name='نام استان ')),
            ],
            options={
                'verbose_name': 'استان',
                'verbose_name_plural': 'استان',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Name', models.CharField(max_length=200, verbose_name='نام شهرستان ')),
                ('IdProvince', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Province', verbose_name='نام استان ')),
            ],
            options={
                'verbose_name': 'شهرستان',
                'verbose_name_plural': 'شهرستان',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='IdCity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.City', verbose_name='شهرستان'),
        ),
        migrations.AddField(
            model_name='user',
            name='IdProvince',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.Province', verbose_name='استان'),
        ),
    ]
