# Generated by Django 2.2.11 on 2021-04-22 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210422_0114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='IdCity',
        ),
        migrations.RemoveField(
            model_name='user',
            name='IdProvince',
        ),
    ]
