# Generated by Django 2.2.11 on 2021-04-22 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20210423_0022'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
    ]
