# Generated by Django 2.2.11 on 2021-04-22 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_delete_city'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Province',
        ),
    ]
