# Generated by Django 2.2.11 on 2021-04-22 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_province'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Name', models.CharField(max_length=200, verbose_name='نام شهرستان ')),
                ('IdProvince', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Province', verbose_name='نام استان ')),
            ],
            options={
                'verbose_name': 'شهرستان',
                'verbose_name_plural': 'شهرستان',
            },
        ),
    ]
