# Generated by Django 2.2.11 on 2021-04-22 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='IdCity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.City', verbose_name='نام شهرستان'),
        ),
    ]
