# Generated by Django 2.2.11 on 2021-04-26 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20210423_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='IdProvince',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.Province', verbose_name='نام استان '),
        ),
        migrations.AlterField(
            model_name='user',
            name='IdCity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.City', verbose_name='نام شهرستان'),
        ),
    ]
