# Generated by Django 2.2.11 on 2021-04-28 16:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20210426_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_storekeeper',
            field=models.BooleanField(default=False, verbose_name='وضعیت انبارداری'),
        ),
        migrations.AddField(
            model_name='user',
            name='storekeeper_user',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='کاربر انباردار تا'),
        ),
    ]
