# Generated by Django 3.2.5 on 2021-08-30 17:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_user_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Bank_CardNumber',
            field=models.TextField(default='-', max_length=100, verbose_name='شماره کارت'),
        ),
        migrations.AddField(
            model_name='user',
            name='Bank_Shaba',
            field=models.TextField(default='-', max_length=100, verbose_name='شماره شبا'),
        ),
        migrations.AddField(
            model_name='user',
            name='FacilitiesWelfare_user',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='کاربر امور رفاهی تا'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_FacilitiesWelfare',
            field=models.BooleanField(default=False, verbose_name='وضعیت امورات رفاهی'),
        ),
    ]
