# Generated by Django 3.2.5 on 2021-08-30 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_auto_20210830_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Bnk_CardNumber',
            field=models.CharField(default='-', max_length=100, verbose_name='شماره کارت'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Bnk_Shaba',
            field=models.CharField(default='-', max_length=100, verbose_name='شماره شبا'),
        ),
    ]
