# Generated by Django 3.2.5 on 2021-08-30 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0014_alter_user_first_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryCommodity',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='کد دسته')),
                ('Name', models.CharField(max_length=100, verbose_name='نام دسته')),
            ],
            options={
                'verbose_name': 'دسته',
                'verbose_name_plural': 'دسته ها',
            },
        ),
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='کد کالا')),
                ('Name', models.CharField(max_length=100, verbose_name='نام کالا')),
                ('UnitPackCount', models.IntegerField(verbose_name='مقدار بسته')),
                ('CommoditySpecifications', models.TextField(verbose_name='مشخصات کالا')),
                ('ExpirationDate', models.DateField(verbose_name='تاریخ مصرف')),
                ('OrderPoint', models.IntegerField(verbose_name='نقطه سفارش')),
                ('MinimumInventory', models.IntegerField(verbose_name='حداقل موجودی')),
                ('OrderAmount', models.IntegerField(verbose_name='میزان سفارش')),
                ('MaximumInventory', models.IntegerField(verbose_name='حداکثر موجودی')),
                ('AddressCommodity', models.TextField(verbose_name='آدرس کالا')),
                ('TechnicalNumber', models.CharField(max_length=100, verbose_name='شماره فنی')),
                ('BarCodeText', models.CharField(max_length=255, verbose_name='بارکد')),
                ('BarCodeImage', models.CharField(max_length=255, verbose_name='بارکد')),
                ('TechnicalSpecifications', models.TextField(blank=True, verbose_name='مشخصات فنی')),
                ('EntryDateTime', models.DateTimeField(auto_now=True)),
                ('UnitPrice', models.IntegerField(verbose_name='بهای واحد')),
                ('Description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('IdCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.categorycommodity', verbose_name='شناسه دسته ')),
            ],
            options={
                'verbose_name': 'کالا',
                'verbose_name_plural': 'کالا ها',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('AccountSideCode', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='کد طرف حساب')),
                ('Name', models.CharField(max_length=200, verbose_name='نام')),
                ('Family', models.CharField(max_length=200, verbose_name='نام خانوادگی')),
                ('Mobile', models.CharField(max_length=10, verbose_name='شماره موبایل')),
                ('TelephoneCustomer', models.CharField(max_length=15, verbose_name='شماره تلفن')),
                ('RegistrationNumber', models.CharField(max_length=20, verbose_name='شماره ثبت')),
                ('EconomicNumber', models.CharField(max_length=20, verbose_name='کدملی/شماره اقتصادی')),
                ('NationalID', models.CharField(max_length=20, verbose_name='شناسه ملی')),
                ('PostalCode', models.CharField(max_length=10, verbose_name='کد پستی')),
                ('Address', models.TextField(verbose_name='آدرس')),
                ('FirstBalanceCourse', models.IntegerField(verbose_name='مانده اول دوره')),
                ('Status', models.CharField(choices=[('A', 'بی حساب'), ('B', 'بدهکار'), ('C', 'بستانکار')], default='A', max_length=1, verbose_name='وضعیت حساب')),
            ],
            options={
                'verbose_name': 'نام مشتری',
                'verbose_name_plural': 'مشتری ها',
            },
        ),
        migrations.CreateModel(
            name='drivers',
            fields=[
                ('DriverCode', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='کد راننده')),
                ('Name', models.CharField(max_length=100, verbose_name='نام')),
                ('Family', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('Telephone', models.CharField(max_length=10, verbose_name='شماره همراه')),
                ('NationalCode', models.CharField(max_length=10, verbose_name='کد ملی')),
                ('LicensePlateNumber', models.CharField(max_length=200, verbose_name='شماره پلاک')),
                ('CarType', models.CharField(max_length=200, verbose_name='نوع ماشین')),
                ('FreightName', models.CharField(max_length=200, verbose_name='نام باربری')),
                ('AccountNumber', models.CharField(max_length=20, verbose_name='شماره حساب')),
                ('Shabanumber', models.CharField(max_length=24, verbose_name='شماره شبا')),
                ('CardNumber', models.CharField(max_length=16, verbose_name='شماره کارت')),
                ('Address', models.CharField(max_length=200, verbose_name='آدرس')),
                ('Description', models.TextField(max_length=200, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'راننده',
                'verbose_name_plural': 'راننده ها',
            },
        ),
        migrations.CreateModel(
            name='EntryCommodity',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='کد کالا')),
                ('Count', models.IntegerField(verbose_name='تعداد')),
                ('DateEntry', models.DateTimeField(verbose_name='تاریخ')),
                ('Description', models.TextField(verbose_name='توضیحات')),
                ('InvoiceNumber', models.CharField(max_length=200, verbose_name='شماره فاکتور')),
                ('Serial', models.CharField(max_length=200, verbose_name='سریال کالا')),
                ('DateExpired', models.DateTimeField(verbose_name='تاریخ انقضا')),
                ('Status', models.CharField(choices=[('i', 'ورود'), ('o', 'خروج'), ('r', 'مرجوعی')], default='i', max_length=1, verbose_name='وضعیت')),
                ('IdCommodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.commodity', verbose_name='نام کالا')),
                ('IdCustomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.customer', verbose_name='نام مشتری')),
            ],
            options={
                'verbose_name': 'ورود کالا',
                'verbose_name_plural': 'ورود کالاها',
            },
        ),
        migrations.CreateModel(
            name='GroupCommodity',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='کد گروه')),
                ('Name', models.CharField(max_length=100, verbose_name='نام گروه')),
            ],
            options={
                'verbose_name': 'گروه',
                'verbose_name_plural': 'گروه\u200f ها',
            },
        ),
        migrations.CreateModel(
            name='Storeroom',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='کدانبار')),
                ('Name', models.CharField(max_length=100, verbose_name='نام انبار')),
                ('Address', models.TextField(verbose_name='آدرس انبار')),
                ('Telephone', models.CharField(max_length=10, verbose_name='شماره تلفن')),
                ('status', models.CharField(choices=[('A', 'فعال'), ('N', 'غیرفعال')], default='A', max_length=1, verbose_name='وضعیت')),
                ('IdCity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.city', verbose_name='شهرستان')),
            ],
            options={
                'verbose_name': 'انبار',
                'verbose_name_plural': 'انبار ها',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='کد تامین کننده')),
                ('Name', models.CharField(max_length=100, verbose_name='نام تامین کننده')),
            ],
            options={
                'verbose_name': 'تامین کننده',
                'verbose_name_plural': 'تامین کننده ها',
            },
        ),
        migrations.CreateModel(
            name='UnitofMeasurement',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='کدواحد سنجش')),
                ('Name', models.CharField(max_length=100, verbose_name='نام واحد سنجش')),
            ],
            options={
                'verbose_name': 'واحد سنجش',
                'verbose_name_plural': 'واحدهای سنجش',
            },
        ),
        migrations.CreateModel(
            name='UnitPack',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='کد بسته')),
                ('Name', models.CharField(max_length=100, verbose_name='نام بسته')),
            ],
            options={
                'verbose_name': 'بسته',
                'verbose_name_plural': 'بسته ها',
            },
        ),
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='کد حمل و نقل')),
                ('Sender', models.CharField(max_length=200, verbose_name='فرستنده')),
                ('Transferee', models.CharField(max_length=200, verbose_name='گیرنده')),
                ('FreightNumber', models.IntegerField(verbose_name='شماره بارنامه')),
                ('SourceAddress', models.CharField(max_length=200, verbose_name='آدرس مبدا')),
                ('Date', models.DateTimeField(auto_now=True, verbose_name='تاریخ ثبت')),
                ('Description', models.TextField(verbose_name='توضیحات')),
                ('IdDrivers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.drivers', verbose_name='نام راننده')),
                ('IdEntryCommodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.entrycommodity', verbose_name='ورود کالا')),
            ],
            options={
                'verbose_name': 'حمل و نقل',
                'verbose_name_plural': 'حمل و نقل',
            },
        ),
        migrations.CreateModel(
            name='TransfersbetweenStoreroom',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='شناسه انتقال')),
                ('Date', models.DateTimeField(auto_now=True, verbose_name='تاریخ ثبت')),
                ('Description', models.TextField(max_length=200, verbose_name='توضیحات')),
                ('IdStoreroomDestination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='StoreroomDestination', to='inventory.storeroom', verbose_name='انبار مقصد')),
                ('IdStoreroomSource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='StoreroomSource', to='inventory.storeroom', verbose_name='انبار مبدا')),
            ],
            options={
                'verbose_name': 'شناسه انتقال',
                'verbose_name_plural': 'نقل و انتقال',
            },
        ),
        migrations.CreateModel(
            name='SettlementArrived',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='شماره سند')),
                ('Type', models.CharField(choices=[('C', 'نقدی'), ('I', 'قسطی')], max_length=1, verbose_name='نوع')),
                ('Date', models.DateTimeField(auto_now=True, verbose_name='تاریخ سند')),
                ('Amount', models.IntegerField(verbose_name='مبلغ')),
                ('Description', models.TextField(max_length=200, verbose_name='توضیحات')),
                ('Address', models.CharField(max_length=200, verbose_name='آدرس')),
                ('Telephone', models.CharField(max_length=10, verbose_name='تلفن')),
                ('ReceiptNumber', models.CharField(max_length=20, verbose_name='شماره سند')),
                ('IdStoreroom', models.ForeignKey(default=29, on_delete=django.db.models.deletion.CASCADE, to='inventory.storeroom', verbose_name='نام انبار')),
            ],
            options={
                'verbose_name': 'تسویه فاکتور',
                'verbose_name_plural': 'تسویه فاکتورها',
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='کد کالا')),
                ('Count', models.IntegerField(verbose_name='تعداد')),
                ('Amount', models.IntegerField(verbose_name='مبلغ جز')),
                ('Discount', models.IntegerField(verbose_name='تخفیف')),
                ('Taxation', models.IntegerField(verbose_name='مالیات')),
                ('Date', models.DateTimeField(auto_now=True, verbose_name='تاریخ فاکتور')),
                ('Type', models.CharField(choices=[('B', 'خرید'), ('S', 'فروش')], max_length=1, verbose_name='نوع')),
                ('IdCommodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.commodity', verbose_name='نام کالا')),
                ('IdCustomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.customer', verbose_name='نام مشتری')),
                ('IdStoreroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.storeroom', verbose_name='نام انبار')),
                ('IdUnitofMeasurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.unitofmeasurement', verbose_name='واحد سنجش')),
            ],
            options={
                'verbose_name': 'فاکتور خرید/فروش',
                'verbose_name_plural': 'فاکتورهای خرید/فروش',
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='شماره درخواست')),
                ('Count', models.IntegerField(verbose_name='تعداد')),
                ('DateRequired', models.DateTimeField(verbose_name='تاریخ نیاز')),
                ('Date', models.DateTimeField(auto_now=True, verbose_name='تاریخ ثبت')),
                ('TechnicalSpecifications', models.TextField(max_length=200, verbose_name='مشخصات فنی')),
                ('PurchaseSource', models.CharField(max_length=20, verbose_name='منبع خرید')),
                ('PurchasingOfficer', models.CharField(max_length=20, verbose_name='مامور خرید')),
                ('Status', models.CharField(choices=[('Y', 'خرید شده'), ('N', 'خرید نشده')], default='N', max_length=1, verbose_name='وضعیت')),
                ('IdCommodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.commodity', verbose_name='نام کالا')),
                ('IdStoreroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.storeroom', verbose_name='نام انبار')),
                ('IdUnitofMeasurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.unitofmeasurement', verbose_name='واحد سنجش')),
            ],
            options={
                'verbose_name': 'درخواست خرید',
                'verbose_name_plural': 'درخواست های خرید',
            },
        ),
        migrations.CreateModel(
            name='productRepaired',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='کد تعمیر')),
                ('SerialNumber', models.CharField(max_length=200, verbose_name='سریال کالا')),
                ('DateRegistration', models.DateTimeField(auto_now=True, verbose_name='تاریخ ثبت')),
                ('DateDelivery', models.DateTimeField(verbose_name='تاریخ تحویل')),
                ('Description', models.TextField(max_length=200, verbose_name='توضیحات')),
                ('Status', models.CharField(choices=[('Y', 'تعمیر شده'), ('N', 'تعمیر نشده')], default='N', max_length=1, verbose_name='وضعیت')),
                ('IdCommodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.commodity', verbose_name='نام کالا')),
                ('IdCustomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.customer', verbose_name='نام مشتری')),
                ('IdStoreroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.storeroom', verbose_name='نام انبار')),
            ],
            options={
                'verbose_name': 'تعمیر کالا',
                'verbose_name_plural': 'تعمیر کالاها',
            },
        ),
        migrations.AddField(
            model_name='entrycommodity',
            name='IdStoreroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.storeroom', verbose_name='نام انبار'),
        ),
        migrations.AddField(
            model_name='commodity',
            name='IdGroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.groupcommodity', verbose_name='شناسه گروه '),
        ),
        migrations.AddField(
            model_name='commodity',
            name='IdStoreroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.storeroom', verbose_name='شناسه انبار '),
        ),
        migrations.AddField(
            model_name='commodity',
            name='IdSupplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.supplier', verbose_name='شناسه تامین کننده '),
        ),
        migrations.AddField(
            model_name='commodity',
            name='IdUnitPack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.unitpack', verbose_name='شناسه بسته '),
        ),
        migrations.AddField(
            model_name='commodity',
            name='IdUnitofMeasurement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.unitofmeasurement', verbose_name='کد واحد سنجش'),
        ),
    ]
