# Generated by Django 3.2.5 on 2021-09-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacilitiesWelfare', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assistance',
            old_name='ConsumerItems',
            new_name='ConsumerTypeItems',
        ),
        migrations.AddField(
            model_name='assistance',
            name='ConsumerType',
            field=models.CharField(choices=[('CA', 'کمک معیشتی'), ('CI', 'اقلام مصرفی'), ('FH', 'کمک بلاعوض')], default=1, max_length=2, verbose_name='نوع'),
            preserve_default=False,
        ),
    ]
