# Generated by Django 3.2.5 on 2021-09-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacilitiesWelfare', '0004_alter_reward_assignmentdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travels',
            name='EndDateTime',
            field=models.DateTimeField(verbose_name='تاریخ پایان'),
        ),
        migrations.AlterField(
            model_name='travels',
            name='StartDateTime',
            field=models.DateTimeField(verbose_name='تاریخ شروع'),
        ),
    ]
