# Generated by Django 3.2.5 on 2021-09-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacilitiesWelfare', '0005_auto_20210928_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerorganizationalhouse',
            name='DateExpire',
            field=models.DateTimeField(verbose_name='تاریخ انقضا'),
        ),
    ]
