# Generated by Django 3.2.5 on 2021-09-29 09:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FacilitiesWelfare', '0008_alter_seeandvisit_datetimeregister'),
    ]

    operations = [
        migrations.AddField(
            model_name='seeandvisit',
            name='DateTimeVisit',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان عیادت'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seeandvisit',
            name='DateTimeRegister',
            field=models.DateTimeField(auto_now=True, verbose_name='زمان ثبت'),
        ),
    ]
