# Generated by Django 3.2.5 on 2021-09-29 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacilitiesWelfare', '0010_cashassistance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashassistance',
            name='TypeAssistance',
            field=models.CharField(blank=True, choices=[('PU', 'همگانی'), ('PR', 'خاص')], default='N', max_length=2, null=True, verbose_name='نوع کمک'),
        ),
    ]
