# Generated by Django 3.2.5 on 2021-09-29 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FacilitiesWelfare', '0011_alter_cashassistance_typeassistance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashassistance',
            name='IdUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='شناسه کاربر'),
        ),
        migrations.AlterField(
            model_name='cashassistance',
            name='TypeAssistance',
            field=models.CharField(choices=[('PU', 'همگانی'), ('PR', 'خاص')], default='N', max_length=2, verbose_name='نوع کمک'),
        ),
    ]
