# Generated by Django 3.2.5 on 2021-09-29 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacilitiesWelfare', '0012_auto_20210929_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashassistance',
            name='Price',
            field=models.IntegerField(default=1, verbose_name='مبلغ کمک'),
            preserve_default=False,
        ),
    ]
