# Generated by Django 3.2.5 on 2021-09-29 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacilitiesWelfare', '0014_auto_20210929_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashassistance',
            name='TypeAssistance',
            field=models.CharField(choices=[('PU', 'همگانی'), ('PR', 'خاص')], default='PU', max_length=2, verbose_name='نوع کمک'),
        ),
    ]
