# Generated by Django 3.2.5 on 2021-09-29 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacilitiesWelfare', '0015_alter_cashassistance_typeassistance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashassistance',
            name='DateRegister',
            field=models.DateTimeField(verbose_name='تاریخ ثبت کمک معیشتی'),
        ),
    ]
