# Generated by Django 3.2.5 on 2021-09-29 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FacilitiesWelfare', '0017_consumeritems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumeritems',
            name='IdUser',
        ),
    ]
