# Generated by Django 3.2.5 on 2021-09-29 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FacilitiesWelfare', '0018_remove_consumeritems_iduser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consumeritems',
            options={'verbose_name': 'قلم مصرفی', 'verbose_name_plural': 'اصلام مصرفی'},
        ),
        migrations.CreateModel(
            name='ConsumerItemsRegister',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='شناسه')),
                ('DateRegister', models.DateTimeField(verbose_name='تاریخ ثبت')),
                ('IdConsumerItems', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FacilitiesWelfare.consumeritems', verbose_name='قلم مصرفی')),
                ('IdUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='شناسه کاربر')),
            ],
            options={
                'verbose_name': 'ثبت نام قلم مصرفی',
                'verbose_name_plural': 'ثبت نام اقلام مصرفی',
            },
        ),
    ]
