# Generated by Django 3.2.5 on 2021-09-29 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_auto_20210830_2200'),
        ('FacilitiesWelfare', '0020_auto_20210929_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationalhouse',
            name='Address',
            field=models.CharField(default=1, max_length=200, verbose_name='آدرس'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizationalhouse',
            name='Floor',
            field=models.IntegerField(default=0, verbose_name='طبقه'),
        ),
        migrations.AddField(
            model_name='organizationalhouse',
            name='IdCity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.city', verbose_name='شهر'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizationalhouse',
            name='Pelaque',
            field=models.IntegerField(default=0, verbose_name='پلاک'),
        ),
        migrations.AddField(
            model_name='organizationalhouse',
            name='PostalCode',
            field=models.CharField(default='-', max_length=200, verbose_name='کدپستی'),
        ),
        migrations.AddField(
            model_name='organizationalhouse',
            name='Unit',
            field=models.IntegerField(default=0, verbose_name='واحد'),
        ),
    ]
