# Generated by Django 3.2.5 on 2021-09-29 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacilitiesWelfare', '0021_auto_20210929_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationalhouse',
            name='PostalCode',
            field=models.CharField(default='-', max_length=10, verbose_name='کدپستی'),
        ),
    ]
