# Generated by Django 3.2.5 on 2021-09-29 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FacilitiesWelfare', '0022_alter_organizationalhouse_postalcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationalhouse',
            name='DateExpire',
        ),
    ]
