# Generated by Django 3.2.5 on 2021-09-30 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FacilitiesWelfare', '0023_remove_organizationalhouse_dateexpire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='IdUser',
        ),
    ]
