# Generated by Django 3.2.5 on 2021-09-30 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FacilitiesWelfare', '0024_remove_project_iduser'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterProject',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='شناسه')),
                ('RegisterDateTime', models.DateTimeField(auto_now=True, verbose_name='تاریخ ثبت')),
                ('IdProject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FacilitiesWelfare.project', verbose_name='کاربر')),
                ('IdUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروژه',
                'verbose_name_plural': 'پروژه ها',
            },
        ),
    ]
