# Generated by Django 3.2.5 on 2021-09-30 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FacilitiesWelfare', '0025_registerproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerproject',
            name='IdProject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FacilitiesWelfare.project', verbose_name='پروژه'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='Description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
    ]
