# Generated by Django 3.2.5 on 2021-09-30 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacilitiesWelfare', '0028_alter_seeandvisit_consumeritems'),
    ]

    operations = [
        migrations.AddField(
            model_name='freehelp',
            name='Price',
            field=models.IntegerField(default=1, verbose_name='مبلغ'),
            preserve_default=False,
        ),
    ]
