# Generated by Django 3.2.5 on 2021-10-01 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacilitiesWelfare', '0029_freehelp_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumeritemsregister',
            name='DateRegister',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ ثبت'),
        ),
    ]
