# Generated by Django 3.2.5 on 2021-10-01 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacilitiesWelfare', '0030_alter_consumeritemsregister_dateregister'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumeritems',
            name='Price',
            field=models.IntegerField(default=1, verbose_name='مبلغ'),
            preserve_default=False,
        ),
    ]
