# Generated by Django 3.2.5 on 2021-10-01 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacilitiesWelfare', '0032_consumeritemsregister_isreceived'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerorganizationalhouse',
            name='IsVerify',
            field=models.CharField(choices=[('Y', 'تایید شده'), ('N', 'تایید نشده')], default=1, max_length=1, verbose_name='تاییدیه'),
            preserve_default=False,
        ),
    ]
