# Generated by Django 3.2.5 on 2021-10-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacilitiesWelfare', '0033_registerorganizationalhouse_isverify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerorganizationalhouse',
            name='IsVerify',
            field=models.CharField(choices=[('Y', 'تایید شده'), ('N', 'تایید نشده')], default='N', max_length=1, verbose_name='تاییدیه'),
        ),
    ]
