from FacilitiesWelfare.views.Projects import *
from FacilitiesWelfare.views.Reward import *
from FacilitiesWelfare.views.Travels import *
from FacilitiesWelfare.views.Loan import *
from FacilitiesWelfare.views.RelativesDeathServices import *
from FacilitiesWelfare.views.OrganizationalHouse import *
from FacilitiesWelfare.views.RegisterOrganizationalHouse import *
from FacilitiesWelfare.views.SeeAndVisit import *
from FacilitiesWelfare.views.CashAssistance import *
from FacilitiesWelfare.views.ConsumerItems import *
from FacilitiesWelfare.views.ConsumerItemsRegister import *
from FacilitiesWelfare.views.FreeHelp import *
from FacilitiesWelfare.views.RegisterProject import *